export const httpErrorCodes = {
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NO_USERNAME_OR_EMAIL: 'NO_USERNAME_OR_EMAIL',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  INVALID_USERNAME: 'INVALID_USERNAME',
  NO_PASSWORD: 'NO_PASSWORD',
  INVALID_TICKET: 'INVALID_TICKET',
  TRIED: 'TRIED',
  INVALID_CODE: 'INVALID_CODE',
  UNKNOWN: 'UNKNOWN',
};
